name: testing

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test-job:
    name: Test Job
    runs-on: windows-latest
    steps:
    - name: Install winget
      uses: Cyberboss/install-winget@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Delta Chat
      run: |
        $process = Start-Process -FilePath "winget" -ArgumentList show 9pjtxx7hn3pk" -RedirectStandardInput "input.txt" -NoNewWindow -PassThru
        Set-Content -Path "input.txt" -Value "Y"
        $process.WaitForExit()
        winget download 9pjtxx7hn3pk
        winget show 9pjtxx7hn3pk
        winget --help
        echo "Y" | winget install 9pjtxx7hn3pk --source=msstore
        Get-ChildItem -Path "$env:TEMP\WinGet"
        dir "$env:TEMP\WinGet"
