name: testing

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test-job:
    name: Test Job
    runs-on: windows-latest
    steps:
    - name: Install WinGet
      run: |
        Invoke-WebRequest -Uri "https://github.com/microsoft/winget-cli/releases/download/v1.10.30-preview/DesktopAppInstaller_Dependencies.zip" -OutFile ".\deps.zip"
        Expand-Archive -Path ".\deps.zip" -DestinationPath "."
        $appxFiles = Get-ChildItem -Path $x64FolderPath -Filter "*.appx"
        foreach ($appxFile in $appxFiles) { Add-AppxPackage -Path $appxFile.FullName }

        Invoke-WebRequest -Uri "https://github.com/microsoft/winget-cli/releases/download/v1.10.30-preview/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle" -OutFile ".\installer.msixbundle"
        Add-AppxPackage -Path ".\installer.msixbundle"
    - name: Install Delta Chat
      run: |
        winget show 9pjtxx7hn3pk --source=msstore --disable-interactivity --accept-source-agreements --accept-package-agreements
        winget download 9pjtxx7hn3pk --source=msstore --disable-interactivity --accept-source-agreements
        winget --help
        winget install 9pjtxx7hn3pk --source=msstore --disable-interactivity --accept-package-agreements
        Get-ChildItem -Path "$env:TEMP\WinGet"
